/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IMaterialSymbolsAddPhotoAlternate: typeof import('~icons/material-symbols/add-photo-alternate')['default']
    IMaterialSymbolsCalendarMonthRounded: typeof import('~icons/material-symbols/calendar-month-rounded')['default']
    IMaterialSymbolsChevronLeftRounded: typeof import('~icons/material-symbols/chevron-left-rounded')['default']
    IMaterialSymbolsChevronRightRounded: typeof import('~icons/material-symbols/chevron-right-rounded')['default']
    IMaterialSymbolsClose: typeof import('~icons/material-symbols/close')['default']
    IMaterialSymbolsCloseRounded: typeof import('~icons/material-symbols/close-rounded')['default']
    IMaterialSymbolsContentPaste: typeof import('~icons/material-symbols/content-paste')['default']
    IMaterialSymbolsDescription: typeof import('~icons/material-symbols/description')['default']
    IMaterialSymbolsDescriptionRounded: typeof import('~icons/material-symbols/description-rounded')['default']
    IMaterialSymbolsDraft: typeof import('~icons/material-symbols/draft')['default']
    IMaterialSymbolsDraftRounded: typeof import('~icons/material-symbols/draft-rounded')['default']
    IMaterialSymbolsErrorCircleRounded: typeof import('~icons/material-symbols/error-circle-rounded')['default']
    IMaterialSymbolsFolderZip: typeof import('~icons/material-symbols/folder-zip')['default']
    IMaterialSymbolsFolderZipRounded: typeof import('~icons/material-symbols/folder-zip-rounded')['default']
    IMaterialSymbolsImage: typeof import('~icons/material-symbols/image')['default']
    IMaterialSymbolsLink: typeof import('~icons/material-symbols/link')['default']
    IMaterialSymbolsMovie: typeof import('~icons/material-symbols/movie')['default']
    IMaterialSymbolsMovieRounded: typeof import('~icons/material-symbols/movie-rounded')['default']
    IMaterialSymbolsMusicNote: typeof import('~icons/material-symbols/music-note')['default']
    IMaterialSymbolsMusicNoteRounded: typeof import('~icons/material-symbols/music-note-rounded')['default']
    IMaterialSymbolsPictureAsPdf: typeof import('~icons/material-symbols/picture-as-pdf')['default']
    IMaterialSymbolsPictureAsPdfRounded: typeof import('~icons/material-symbols/picture-as-pdf-rounded')['default']
    IMaterialSymbolsRedo: typeof import('~icons/material-symbols/redo')['default']
    IMaterialSymbolsScheduleRounded: typeof import('~icons/material-symbols/schedule-rounded')['default']
    IMaterialSymbolsTableChart: typeof import('~icons/material-symbols/table-chart')['default']
    IMaterialSymbolsTableChartRounded: typeof import('~icons/material-symbols/table-chart-rounded')['default']
    IMaterialSymbolsUndo: typeof import('~icons/material-symbols/undo')['default']
    IMaterialSymbolsUploadFile: typeof import('~icons/material-symbols/upload-file')['default']
    IMaterialSymbolsUploadFileRounded: typeof import('~icons/material-symbols/upload-file-rounded')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const IMaterialSymbolsAddPhotoAlternate: typeof import('~icons/material-symbols/add-photo-alternate')['default']
  const IMaterialSymbolsCalendarMonthRounded: typeof import('~icons/material-symbols/calendar-month-rounded')['default']
  const IMaterialSymbolsChevronLeftRounded: typeof import('~icons/material-symbols/chevron-left-rounded')['default']
  const IMaterialSymbolsChevronRightRounded: typeof import('~icons/material-symbols/chevron-right-rounded')['default']
  const IMaterialSymbolsClose: typeof import('~icons/material-symbols/close')['default']
  const IMaterialSymbolsCloseRounded: typeof import('~icons/material-symbols/close-rounded')['default']
  const IMaterialSymbolsContentPaste: typeof import('~icons/material-symbols/content-paste')['default']
  const IMaterialSymbolsDescription: typeof import('~icons/material-symbols/description')['default']
  const IMaterialSymbolsDescriptionRounded: typeof import('~icons/material-symbols/description-rounded')['default']
  const IMaterialSymbolsDraft: typeof import('~icons/material-symbols/draft')['default']
  const IMaterialSymbolsDraftRounded: typeof import('~icons/material-symbols/draft-rounded')['default']
  const IMaterialSymbolsErrorCircleRounded: typeof import('~icons/material-symbols/error-circle-rounded')['default']
  const IMaterialSymbolsFolderZip: typeof import('~icons/material-symbols/folder-zip')['default']
  const IMaterialSymbolsFolderZipRounded: typeof import('~icons/material-symbols/folder-zip-rounded')['default']
  const IMaterialSymbolsImage: typeof import('~icons/material-symbols/image')['default']
  const IMaterialSymbolsLink: typeof import('~icons/material-symbols/link')['default']
  const IMaterialSymbolsMovie: typeof import('~icons/material-symbols/movie')['default']
  const IMaterialSymbolsMovieRounded: typeof import('~icons/material-symbols/movie-rounded')['default']
  const IMaterialSymbolsMusicNote: typeof import('~icons/material-symbols/music-note')['default']
  const IMaterialSymbolsMusicNoteRounded: typeof import('~icons/material-symbols/music-note-rounded')['default']
  const IMaterialSymbolsPictureAsPdf: typeof import('~icons/material-symbols/picture-as-pdf')['default']
  const IMaterialSymbolsPictureAsPdfRounded: typeof import('~icons/material-symbols/picture-as-pdf-rounded')['default']
  const IMaterialSymbolsRedo: typeof import('~icons/material-symbols/redo')['default']
  const IMaterialSymbolsScheduleRounded: typeof import('~icons/material-symbols/schedule-rounded')['default']
  const IMaterialSymbolsTableChart: typeof import('~icons/material-symbols/table-chart')['default']
  const IMaterialSymbolsTableChartRounded: typeof import('~icons/material-symbols/table-chart-rounded')['default']
  const IMaterialSymbolsUndo: typeof import('~icons/material-symbols/undo')['default']
  const IMaterialSymbolsUploadFile: typeof import('~icons/material-symbols/upload-file')['default']
  const IMaterialSymbolsUploadFileRounded: typeof import('~icons/material-symbols/upload-file-rounded')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}