/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IMaterialSymbolsClose: typeof import('~icons/material-symbols/close')['default']
    IMaterialSymbolsErrorCircleRounded: typeof import('~icons/material-symbols/error-circle-rounded')['default']
    IMaterialSymbolsSearchRounded: typeof import('~icons/material-symbols/search-rounded')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const IMaterialSymbolsClose: typeof import('~icons/material-symbols/close')['default']
  const IMaterialSymbolsErrorCircleRounded: typeof import('~icons/material-symbols/error-circle-rounded')['default']
  const IMaterialSymbolsSearchRounded: typeof import('~icons/material-symbols/search-rounded')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}